/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import clases.Armas_C;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.logging.Logger;
import static window.Bienvenida.pathArmas;
import static window.Armas.contenedor_armas;
import static window.Armas.nombre_arma;
/**
 *
 * @author luedu
 */
public class Armas extends javax.swing.JFrame {

    public static LinkedList contenedor_armas = new LinkedList();
    public int buscar;
  
    /**
     * Creates new form Inicio1
     */
    public Armas() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
    /**
 * Método para Guardar en Lenguaje Máquina
 * @param evt 
 */
      public void createBin(){
        ObjectOutputStream binario = null;
        try {
            String nameFile = nombre_arma.getText();
            File file = new File(nameFile);
            Armas_C gun = (Armas_C) contenedor_armas.getLast();
           
            binario = new ObjectOutputStream(new FileOutputStream(pathArmas+gun.getArma()+".arm"));
            binario.writeObject(gun);
            
        } catch (Exception ex) {
            ex.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException ex) {
                Logger.getLogger(Armas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ver_Armas = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        GArmas = new javax.swing.JButton();
        N_Arma = new javax.swing.JLabel();
        nombre_arma = new javax.swing.JTextField();
        N_Daño = new javax.swing.JLabel();
        Daño = new javax.swing.JTextField();
        N_Velocidad = new javax.swing.JLabel();
        Velocidad = new javax.swing.JTextField();
        N_Precio = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        Presicion = new javax.swing.JTextField();
        N_Presicion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver_Armas.setBackground(new java.awt.Color(102, 255, 0));
        Ver_Armas.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Ver_Armas.setText("Armas");
        Ver_Armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_ArmasActionPerformed(evt);
            }
        });
        getContentPane().add(Ver_Armas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 690, 100, 50));

        Bback.setBackground(new java.awt.Color(102, 255, 0));
        Bback.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        getContentPane().add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 50));

        GArmas.setBackground(new java.awt.Color(102, 255, 0));
        GArmas.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        GArmas.setText("Guardar");
        GArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GArmasActionPerformed(evt);
            }
        });
        getContentPane().add(GArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 130, 50));

        N_Arma.setBackground(new java.awt.Color(102, 255, 102));
        N_Arma.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        N_Arma.setForeground(new java.awt.Color(255, 0, 0));
        N_Arma.setText("Nombre:");
        N_Arma.setAutoscrolls(true);
        getContentPane().add(N_Arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        nombre_arma.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        nombre_arma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_armaActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 340, 30));

        N_Daño.setBackground(new java.awt.Color(0, 0, 204));
        N_Daño.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Daño.setForeground(new java.awt.Color(51, 0, 204));
        N_Daño.setText("Daño:");
        N_Daño.setAutoscrolls(true);
        getContentPane().add(N_Daño, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        Daño.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Daño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Daño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DañoActionPerformed(evt);
            }
        });
        getContentPane().add(Daño, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 230, 30));

        N_Velocidad.setBackground(new java.awt.Color(0, 0, 204));
        N_Velocidad.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Velocidad.setForeground(new java.awt.Color(51, 0, 204));
        N_Velocidad.setText("Velocidad:");
        N_Velocidad.setAutoscrolls(true);
        getContentPane().add(N_Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        Velocidad.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Velocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Velocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 230, 30));

        N_Precio.setBackground(new java.awt.Color(0, 0, 204));
        N_Precio.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Precio.setForeground(new java.awt.Color(255, 255, 0));
        N_Precio.setText("Precio:");
        N_Precio.setAutoscrolls(true);
        getContentPane().add(N_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        Precio.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 230, 30));

        Presicion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Presicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Presicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresicionActionPerformed(evt);
            }
        });
        getContentPane().add(Presicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 230, 30));

        N_Presicion.setBackground(new java.awt.Color(0, 0, 204));
        N_Presicion.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Presicion.setForeground(new java.awt.Color(51, 0, 204));
        N_Presicion.setText("Presición:");
        N_Presicion.setAutoscrolls(true);
        getContentPane().add(N_Presicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        this.setVisible(false);
        new Tienda().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BbackActionPerformed
/**
 * Método para crear Armas
 * @param evt 
 */
    
    private void GArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GArmasActionPerformed
      
        String N_Arma = nombre_arma.getText();
        String N_Presicion = Presicion.getText();
        String N_Daño = Daño.getText();
        String N_Velocidad = Velocidad.getText();
        String N_Precio = Precio.getText();
  
        
        
        Armas_C  arm = new Armas_C(N_Arma, N_Presicion, N_Daño, N_Velocidad, N_Precio);
        contenedor_armas.add(arm);
        //Limpia
        nombre_arma.setText("");
        Presicion.setText("");
        Daño.setText("");
        Velocidad.setText("");
        Precio.setText("");
     
        
        Armas_C armm = (Armas_C)contenedor_armas.getLast();
        createBin();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_GArmasActionPerformed

    private void DañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DañoActionPerformed

    private void VelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadActionPerformed

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void PresicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresicionActionPerformed

  /**
 * Método ver Armas
 * @param evt 
 */
    private void Ver_ArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_ArmasActionPerformed
     
      Armas principa2 = new Armas();
      principa2.show();
      principa2.setVisible(false);
      
        
        this.setVisible(false);
        new T_Armas().setVisible(true);// TODO add your handling code here:
    
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver_ArmasActionPerformed

    private void nombre_armaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_armaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_armaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Armas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Armas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Armas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Armas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Armas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    public static javax.swing.JTextField Daño;
    private javax.swing.JButton GArmas;
    private javax.swing.JLabel N_Arma;
    private javax.swing.JLabel N_Daño;
    private javax.swing.JLabel N_Precio;
    private javax.swing.JLabel N_Presicion;
    private javax.swing.JLabel N_Velocidad;
    public static javax.swing.JTextField Precio;
    public static javax.swing.JTextField Presicion;
    public static javax.swing.JTextField Velocidad;
    private javax.swing.JButton Ver_Armas;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField nombre_arma;
    // End of variables declaration//GEN-END:variables

    private String getArma() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}