/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import clases.Aviones_C;
import clases.HTML_V;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static window.Bienvenida.pathAviones;


/**
 *
 * @author luedu
 */
public class Aviones extends javax.swing.JFrame {
    
    public static LinkedList contenedor_avion = new LinkedList();
    public int buscar;
    
    
    
    public static ArrayList<Aviones_C> avv = new ArrayList<>();
    File lista_av = new File("Listado de Aviones.html");
    
    
    HTML_V ht = new HTML_V();
    
   

    /**
     * Creates new form Inicio1
     */
    public Aviones() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    /**
 * Método para Archivos de Aviones
 * @param evt 
 */
      public void createBin(){
        ObjectOutputStream binario = null;
        try {
            String nameFile = nombre_avion.getText();
            File file = new File(nameFile);
            Aviones_C Airplane = (Aviones_C) contenedor_avion.getLast();
           
            binario = new ObjectOutputStream(new FileOutputStream(pathAviones+Airplane.getAvion()+".avion"));
            binario.writeObject(Airplane);
            
        } catch (Exception e) {
            e.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException e) {
                Logger.getLogger(Aviones.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
    }
      
       public void reportes1(){
                 try {
              FileWriter aa = new FileWriter(lista_av);
              BufferedWriter bw = new BufferedWriter(aa);
             
             ht.generarEncabezado("Listado de Aviones");
             ht.generarpestania("Nombre", "Presicion", "Ataque", "Precio      Activo");
             bw.write(ht.salida);
             bw.newLine();
             for(int i =0; i<avv.size();i++){
                  ht.generarFilaHTML(avv.get(i).N_Avion, avv.get(i).N_Presicion, avv.get(i).N_Ataque, avv.get(i).N_Precio);
                  bw.write(ht.filatxt);
                  bw.newLine();
              }
             ht.generarCola();
             bw.write(ht.cola);
             bw.newLine();
             bw.close();
             aa.close();
          } catch (Exception e) {
              
          }
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ver_Aviones = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        GAviones = new javax.swing.JButton();
        N_Arma = new javax.swing.JLabel();
        nombre_avion = new javax.swing.JTextField();
        N_Ataque = new javax.swing.JLabel();
        Ataque = new javax.swing.JTextField();
        N_Defensa = new javax.swing.JLabel();
        Defensa = new javax.swing.JTextField();
        N_Precio = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        Presicion = new javax.swing.JTextField();
        N_Presicion = new javax.swing.JLabel();
        N_Velocidad = new javax.swing.JLabel();
        Velocidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver_Aviones.setBackground(new java.awt.Color(102, 255, 0));
        Ver_Aviones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Ver_Aviones.setText("Aviones");
        Ver_Aviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_AvionesActionPerformed(evt);
            }
        });
        getContentPane().add(Ver_Aviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 130, 50));

        Bback.setBackground(new java.awt.Color(102, 255, 0));
        Bback.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        getContentPane().add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 50));

        GAviones.setBackground(new java.awt.Color(102, 255, 0));
        GAviones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        GAviones.setText("Guardar");
        GAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAvionesActionPerformed(evt);
            }
        });
        getContentPane().add(GAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 130, 50));

        N_Arma.setBackground(new java.awt.Color(102, 255, 102));
        N_Arma.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        N_Arma.setForeground(new java.awt.Color(255, 0, 0));
        N_Arma.setText("Nombre:");
        N_Arma.setAutoscrolls(true);
        getContentPane().add(N_Arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        nombre_avion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        nombre_avion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_avion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_avionActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 340, 30));

        N_Ataque.setBackground(new java.awt.Color(0, 0, 204));
        N_Ataque.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Ataque.setForeground(new java.awt.Color(51, 0, 204));
        N_Ataque.setText("Ataque:");
        N_Ataque.setAutoscrolls(true);
        getContentPane().add(N_Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        Ataque.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Ataque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 230, 30));

        N_Defensa.setBackground(new java.awt.Color(0, 0, 204));
        N_Defensa.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Defensa.setForeground(new java.awt.Color(51, 0, 204));
        N_Defensa.setText("Defensa:");
        N_Defensa.setAutoscrolls(true);
        getContentPane().add(N_Defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        Defensa.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Defensa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefensaActionPerformed(evt);
            }
        });
        getContentPane().add(Defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 230, 30));

        N_Precio.setBackground(new java.awt.Color(0, 0, 204));
        N_Precio.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Precio.setForeground(new java.awt.Color(255, 255, 51));
        N_Precio.setText("Precio:");
        N_Precio.setAutoscrolls(true);
        getContentPane().add(N_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        Precio.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 230, 30));

        Presicion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Presicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Presicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresicionActionPerformed(evt);
            }
        });
        getContentPane().add(Presicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 230, 30));

        N_Presicion.setBackground(new java.awt.Color(0, 0, 204));
        N_Presicion.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Presicion.setForeground(new java.awt.Color(51, 0, 204));
        N_Presicion.setText("Presición:");
        N_Presicion.setAutoscrolls(true);
        getContentPane().add(N_Presicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        N_Velocidad.setBackground(new java.awt.Color(0, 0, 204));
        N_Velocidad.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        N_Velocidad.setForeground(new java.awt.Color(51, 0, 204));
        N_Velocidad.setText("Velocidad:");
        N_Velocidad.setAutoscrolls(true);
        getContentPane().add(N_Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        Velocidad.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Velocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Velocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/untitled.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        this.setVisible(false);
        new Tienda().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BbackActionPerformed

 /**
 * Método para guardar Aviones
 * @param evt 
 */
    private void GAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAvionesActionPerformed
    
        String N_Tanque = nombre_avion.getText();
        String N_Presicion = Presicion.getText();
        String N_Ataque = Ataque.getText();
        String N_Defensa = Defensa.getText();
        String N_Velocidad = Velocidad.getText();
        String N_Precio = Precio.getText();
  
    
    
   
        //NOMBRE DE LA PERSONA ATRUBUTOS
      
        Aviones_C av  = new Aviones_C (N_Tanque, N_Presicion,N_Ataque, N_Defensa, N_Velocidad, N_Precio);
        contenedor_avion.add(av);
        avv.add(av);
      
        //Limpia
        nombre_avion.setText("");
        Presicion.setText("");
        Ataque.setText("");
        Defensa.setText("");
        Velocidad.setText("");
        Precio.setText("");
        
        Aviones_C p = (Aviones_C)contenedor_avion.getLast();
        createBin();
        
        reportes1();
// TODO
        
        // TODO add your handling code here:
    }//GEN-LAST:event_GAvionesActionPerformed

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtaqueActionPerformed

    private void DefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefensaActionPerformed

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void PresicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresicionActionPerformed

    private void VelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadActionPerformed

    private void Ver_AvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_AvionesActionPerformed
        this.setVisible(false);
        new T_Aviones().setVisible(true);// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_Ver_AvionesActionPerformed

    private void nombre_avionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_avionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_avionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aviones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Ataque;
    private javax.swing.JButton Bback;
    public static javax.swing.JTextField Defensa;
    private javax.swing.JButton GAviones;
    private javax.swing.JLabel N_Arma;
    private javax.swing.JLabel N_Ataque;
    private javax.swing.JLabel N_Defensa;
    private javax.swing.JLabel N_Precio;
    private javax.swing.JLabel N_Presicion;
    private javax.swing.JLabel N_Velocidad;
    public static javax.swing.JTextField Precio;
    public static javax.swing.JTextField Presicion;
    public static javax.swing.JTextField Velocidad;
    private javax.swing.JButton Ver_Aviones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField nombre_avion;
    // End of variables declaration//GEN-END:variables
}
