/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.util.Random;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author luedu
 */
public class Dado_C extends javax.swing.JFrame {

    /**
     * Creates new form Dado_M
     */
    public Dado_C() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }
    
  /**
 * Método para el valor _Comodin
 * @param evt 
 */
 
        public int valorcomodin(){
        int valor;
        Random rgen = new Random();
        valor = rgen.nextInt(5);

        return valor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valor = new javax.swing.JLabel();
        V_Comodin = new javax.swing.JButton();
        Usar = new javax.swing.JButton();
        Tirar_Dado1 = new javax.swing.JLabel();
        No_Dado = new javax.swing.JLabel();
        Valor1 = new javax.swing.JLabel();
        Valor2 = new javax.swing.JLabel();
        Valor3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Valor.setBackground(new java.awt.Color(102, 255, 102));
        Valor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 153, 0));
        Valor.setText("Valor: ");

        V_Comodin.setBackground(new java.awt.Color(102, 255, 102));
        V_Comodin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        V_Comodin.setForeground(new java.awt.Color(255, 0, 51));
        V_Comodin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/dado.png"))); // NOI18N
        V_Comodin.setActionCommand("Ver Reportes");
        V_Comodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_ComodinActionPerformed(evt);
            }
        });

        Usar.setBackground(new java.awt.Color(102, 255, 102));
        Usar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Usar.setForeground(new java.awt.Color(255, 0, 51));
        Usar.setText("Usar");
        Usar.setActionCommand("Ver Reportes");
        Usar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsarActionPerformed(evt);
            }
        });

        Tirar_Dado1.setBackground(new java.awt.Color(102, 255, 102));
        Tirar_Dado1.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        Tirar_Dado1.setForeground(new java.awt.Color(51, 51, 51));
        Tirar_Dado1.setText("Comodín");

        No_Dado.setBackground(new java.awt.Color(102, 255, 102));
        No_Dado.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        No_Dado.setForeground(new java.awt.Color(51, 51, 51));

        Valor1.setBackground(new java.awt.Color(102, 255, 102));
        Valor1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Valor1.setForeground(new java.awt.Color(255, 153, 0));
        Valor1.setText("1: Abrir");

        Valor2.setBackground(new java.awt.Color(102, 255, 102));
        Valor2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Valor2.setForeground(new java.awt.Color(255, 153, 0));
        Valor2.setText("0 y 3: Random");

        Valor3.setBackground(new java.awt.Color(102, 255, 102));
        Valor3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Valor3.setForeground(new java.awt.Color(255, 153, 0));
        Valor3.setText("2 y 4: Seguir ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tirar_Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Usar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(Valor))
                                .addComponent(V_Comodin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(No_Dado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Tirar_Dado1)
                .addGap(18, 18, 18)
                .addComponent(V_Comodin)
                .addGap(33, 33, 33)
                .addComponent(Valor)
                .addGap(18, 18, 18)
                .addComponent(No_Dado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor2)
                    .addComponent(Valor1)
                    .addComponent(Valor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Usar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
        
    private void V_ComodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_ComodinActionPerformed
         String valor1 = String.valueOf(valorcomodin());
         No_Dado.setText(valor1);
      
    }//GEN-LAST:event_V_ComodinActionPerformed

    private void UsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsarActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_UsarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dado_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dado_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dado_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dado_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dado_C().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel No_Dado;
    private javax.swing.JLabel Tirar_Dado1;
    private javax.swing.JButton Usar;
    public static javax.swing.JButton V_Comodin;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel Valor1;
    private javax.swing.JLabel Valor2;
    private javax.swing.JLabel Valor3;
    // End of variables declaration//GEN-END:variables
}
