/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

/**
 *
 * @author luedu
 */
public class Eleccion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio1
     */
    public Eleccion() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        V_Armas = new javax.swing.JButton();
        V_Aviones = new javax.swing.JButton();
        V_Tanques = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        V_Armas.setBackground(new java.awt.Color(102, 255, 0));
        V_Armas.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        V_Armas.setText("Armas");
        V_Armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_ArmasActionPerformed(evt);
            }
        });
        getContentPane().add(V_Armas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 230, 50));

        V_Aviones.setBackground(new java.awt.Color(102, 255, 0));
        V_Aviones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        V_Aviones.setText("Aviones");
        V_Aviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_AvionesActionPerformed(evt);
            }
        });
        getContentPane().add(V_Aviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 230, 50));

        V_Tanques.setBackground(new java.awt.Color(102, 255, 0));
        V_Tanques.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        V_Tanques.setText("Tanques");
        V_Tanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_TanquesActionPerformed(evt);
            }
        });
        getContentPane().add(V_Tanques, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 230, 50));

        Bback.setBackground(new java.awt.Color(102, 255, 0));
        Bback.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        getContentPane().add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 50));

        Exit.setBackground(new java.awt.Color(102, 255, 0));
        Exit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void V_AvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_AvionesActionPerformed
        Aviones principa2 = new Aviones();
        principa2.show();
        principa2.setVisible(false);
       
        T_Aviones principal = new T_Aviones();
        principal.show();
        this.setVisible(false); 

    }//GEN-LAST:event_V_AvionesActionPerformed

    private void V_TanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_TanquesActionPerformed
        Tanques principa2 = new Tanques();
        principa2.show();
        principa2.setVisible(false);
       
        T_Tanques principal = new T_Tanques();
        principal.show();
        this.setVisible(false); 
  
//    add your handling code here:
    }//GEN-LAST:event_V_TanquesActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        this.setVisible(false);
        new Eleccion().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BbackActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void V_ArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_ArmasActionPerformed
        Armas principa2 = new Armas();
        principa2.show();
        principa2.setVisible(false);
       
        T_Armas principal = new T_Armas();
        principal.show();
        this.setVisible(false); 

        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_V_ArmasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Exit;
    private javax.swing.JButton V_Armas;
    private javax.swing.JButton V_Aviones;
    private javax.swing.JButton V_Tanques;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
