/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import clases.Casilla;
import clases.CasillaAgua;
import clases.CasillaMontaña;
import clases.Persona;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class G_Escenarios extends javax.swing.JFrame {
   
     Casilla[][] tablero;
 

    /**   
     * Creates new form Estadisticas 
     */
    public G_Escenarios() {
        initComponents();
        this.setLocationRelativeTo(null);
         }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Batalla");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 30, 280, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 1063, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void gTablero(int filas, int columnas){
    BorderLayout b = new BorderLayout();
   
 
        tablero =  new Casilla[filas][columnas];
         boolean blanco = true;
         System.out.println("filas" + filas);
        for (int i = 0; i<filas; i++){
            for (int j = 0; j<columnas; j++){

                blanco = !blanco;
                tablero[i][j] = new Casilla ();
               tablero[i][j].setSize(50, 50);
                if (blanco)
                    tablero[i][j].setBackground(Color.white);
                else
                    tablero[i][j].setBackground(Color.white);
                
                tablero[i][j].setVisible(true);

                tablero[i][j].setBounds((50*j), 50*i, 50, 50);
               

                this.remove(panelTablero);
                 this.add(tablero[i][j], BorderLayout.CENTER);
               this.add(panelTablero);
                     panelTablero.add(tablero[i][j]);
            panelTablero.repaint();
            tablero[i][j].removeAll();
            
            }
            
            blanco = !blanco;
        }
   }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_Escenarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
