/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import clases.Escenario_E;
import clases.E_Montaña;
import clases.E_Agua;
import clases.E_Terreno;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author luedu
 */
public class G_Escenarios extends javax.swing.JFrame {
    int turno, contp, contmp;
    boolean gano= false;
    int largo, alto;
    int pos1, pos2, filaVehiculos, columnaVehiculo;
            
  Escenario_E[][] tablero;
  int[][] juego =null;
    /**
     * constructor
     * Creates new form Escenarios
     */
    public G_Escenarios() {
        initComponents();
         this.setLocationRelativeTo(null);
          turno = contp = contmp = 1;
          
        //tablero = new Casilla[8][8];
    }
    
        public void mover(int fe, int ce, int fv, int cv){
        if(fe==fv || ce==cv){
            /*
            if(fe<fv){
                Izquierda(total, fe, ce);
            }else if(fe>fv){
                Derecha(total, fe, ce);
            }else if(ce<cv){
                Arriba(total, fe, ce);
            }else if(ce>cv){
                Abajo(total, fe, ce);
            }else{}
            */
        }else{
            JOptionPane.showMessageDialog(null, "Movimiento Invalido");
        }
    }
    
    
    private void Tablero() {
        
            for (int fila = 0; fila < largo; fila++) {
            System.out.println("");
            for (int columna = 0; columna < alto; columna++) {
                System.out.print(juego[fila][columna] + ", ");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtras = new javax.swing.JButton();
        jButtonDados = new javax.swing.JButton();
        jButtonHaciaE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8x9 = new javax.swing.JButton();
        jButton4x4 = new javax.swing.JButton();
        jButton6x4 = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAtras.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(0, 255, 0));
        jButtonAtras.setText("Back");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 850, 100, 40));

        jButtonDados.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDados.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jButtonDados.setForeground(new java.awt.Color(51, 51, 51));
        jButtonDados.setText("Dado");
        jButtonDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 100, 40));

        jButtonHaciaE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHaciaE.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jButtonHaciaE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonHaciaE.setText("Exit");
        jButtonHaciaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHaciaEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHaciaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 800, 200, 80));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Batalla");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 340, 40));

        jButton8x9.setBackground(new java.awt.Color(255, 255, 255));
        jButton8x9.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton8x9.setForeground(new java.awt.Color(0, 255, 0));
        jButton8x9.setText("8 x 9");
        jButton8x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8x9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 140, 60));

        jButton4x4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4x4.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton4x4.setForeground(new java.awt.Color(0, 255, 0));
        jButton4x4.setText("4 x 4");
        jButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, 60));

        jButton6x4.setBackground(new java.awt.Color(255, 255, 255));
        jButton6x4.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButton6x4.setForeground(new java.awt.Color(0, 255, 0));
        jButton6x4.setText("6  x 4");
        jButton6x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 140, 60));

        panelTablero.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 730, 610));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    /**
     * Método para Salir
     * @param evt 
     */
    private void jButtonHaciaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHaciaEActionPerformed
       this.setVisible(false);
       new Bienvenida().setVisible(true);
   
        //new OpcionesFinales().setVisible(true);
     /*   
        OpcionesFinales entrada3 = new OpcionesFinales();
        entrada3.show();
        entrada3.setSize(825, 866);
            dispose();  */  
    }//GEN-LAST:event_jButtonHaciaEActionPerformed
    /**
     * Método para mostrar el escenario Generico
     * @param filas
     * @param columnas 
     */
    public void gTablero(int filas, int columnas){
    BorderLayout b = new BorderLayout();
    largo=filas;
    alto=columnas;
 
        tablero =  new Escenario_E[filas][columnas];
        juego = new int[filas][columnas];
        Random n = new Random();
         boolean blanco = true;
         System.out.println("filas" + filas);
        for (int i = 0; i<filas; i++){
            for (int j = 0; j<columnas; j++){
                
                int c = (int)((Math.random()*3)+1);
                System.out.println(c);
                switch(c){
                    case 1: 
                        juego[i][j]= 1;
                        tablero[i][j] = new Escenario_E ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new E_Terreno();
                          break;
                    case 2:
                        juego[i][j]= 2;
                        tablero[i][j] = new Escenario_E ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new E_Montaña();
                          break;
                    case 3:
                        juego[i][j]= 3;
                        tablero[i][j] = new Escenario_E ();
                         tablero[i][j].setBounds((50*j), 50*i, 50, 50);
                          tablero[i][j]= new E_Agua();
                    break;
                    default:
                    break;
                    
                }
                 Pieza accion = new Pieza();
                tablero[i][j].addActionListener(accion);
                tablero[i][j].setVisible(true);

                tablero[i][j].setBounds((50*j), 50*i, 50, 50);
               
                panelTablero.add(tablero[i][j]);
                panelTablero.updateUI();
                panelTablero.setLayout(new GridLayout(filas, columnas));
                panelTablero.repaint();
            }
           
            blanco = !blanco;
        }
        
        int d = (int) (Math.random()*4);
        int d2 = (int) (Math.random()*4);
        ImageIcon tanque = new ImageIcon("src/picture/tanque_T.png");
        Icon iconoTanque = new ImageIcon(tanque.getImage().getScaledInstance(55, 55, Image.SCALE_SMOOTH));
        tablero[d][d2].setIcon(iconoTanque);
        juego[d][d2] = 5;
        filaVehiculos=d;
        columnaVehiculo=d2;
        
        int a =  (int) (Math.random()*4);
        int a2 = (int) (Math.random()*4);
        ImageIcon avion = new ImageIcon("src/picture/avion_T.png");
        Icon iconoAvion = new ImageIcon(avion.getImage().getScaledInstance(55, 55, Image.SCALE_SMOOTH));
        tablero[a][a2].setIcon(iconoAvion);
        juego[a][a2] = 4;
        
        int c = (int) (Math.random()*4);
        int c2 = (int) (Math.random()*4);
            ImageIcon comodin = new ImageIcon("src/picture/gift.png");
        Icon iconoComodin = new ImageIcon(comodin.getImage().getScaledInstance(45, 45, Image.SCALE_SMOOTH));
         tablero[c][c2].setIcon(iconoComodin);
        juego[c][c2] = 4;
        
        
        Tablero();
}
    
        private class Pieza implements ActionListener {

        int vida=100;
        
        @Override
        public void actionPerformed(ActionEvent click) {
            for (int fila1 = 0; fila1 < largo; fila1++) {
                for (int columna = 0; columna < alto; columna++) {
                    if (click.getSource().equals(tablero[fila1][columna])) {
                       
                        pos1 = fila1;
                        pos2 = columna;
                        int f;
                            switch(juego[fila1][columna]){
                                case 1:
                                    //Distancia(pos1, pos2, filaVehiculos, columnaVehiculo);
                                    mover(pos1, pos2, filaVehiculos, columnaVehiculo);
                                    break;
                                case 2:
                                    f = (int)(Math.random()*100);
                                    vida=vida-f;
                                    vidas(fila1, columna);
                                    break;
                                case 3:
                                    f = (int)(Math.random()*100);
                                    vida=vida-f;
                                    vidas(fila1, columna);
                                    break;
                        }             
                        
                        System.out.println(tablero[fila1][columna].getColorModel());
                        System.out.println("Fila " + fila1 + " Columna " + columna);
                        System.out.println(juego[fila1][columna]);


                    }
                }
            }
        }

        private void vidas(int fila1, int columna){
            if(vida<=0){
                juego[fila1][columna] = 1;
                tablero[fila1][columna].setBackground(Color.gray);
            }else{}
        }
    }

    
    
    
    /**
     * Método para Generar Randoms
     * @param N
     * @param M 
     */
    public void metodoRandom(int N, int M){
        Random n = new Random();
        n.nextInt(5);
        n.nextInt(6);
        
        
    }
    
    
    private void jButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x4ActionPerformed
        panelTablero.removeAll();
        jButton6x4.setVisible(false);
        jButton8x9.setVisible(false);
        gTablero(4, 4);
       
        
    }//GEN-LAST:event_jButton4x4ActionPerformed

    private void jButton6x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x4ActionPerformed
        jButton4x4.setVisible(false);
        jButton8x9.setVisible(false);
       panelTablero.removeAll();
        gTablero(6, 4);
    }//GEN-LAST:event_jButton6x4ActionPerformed

    private void jButton8x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x9ActionPerformed
         panelTablero.removeAll();
         jButton4x4.setVisible(false);
         jButton6x4.setVisible(false);
        gTablero(8, 9);
    }//GEN-LAST:event_jButton8x9ActionPerformed

    private void jButtonDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosActionPerformed
       new Elegir_Dados().setVisible(true);       
    }//GEN-LAST:event_jButtonDadosActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
       this.setVisible(false);
       new TipoPartida().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_Escenarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_Escenarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4x4;
    private javax.swing.JButton jButton6x4;
    private javax.swing.JButton jButton8x9;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonDados;
    private javax.swing.JButton jButtonHaciaE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
