/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

/**
 *
 * @author luedu
 */
public class Option extends javax.swing.JFrame {

    /**
     * Creates new form Inicio1
     */
    public Option() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BNuevo = new javax.swing.JButton();
        BCargar = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        Tienda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BNuevo.setBackground(new java.awt.Color(102, 255, 0));
        BNuevo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BNuevo.setText("Nueva Partida");
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 230, 50));

        BCargar.setBackground(new java.awt.Color(102, 255, 0));
        BCargar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BCargar.setText("Cargar Partida");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });
        getContentPane().add(BCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 230, 50));

        Bback.setBackground(new java.awt.Color(102, 255, 0));
        Bback.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        getContentPane().add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 50));

        Tienda.setBackground(new java.awt.Color(102, 255, 0));
        Tienda.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Tienda.setText("Tienda");
        Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiendaActionPerformed(evt);
            }
        });
        getContentPane().add(Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Descargar Pack Fondos de Pantalla Mejores juegos (310)4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        this.setVisible(false);
        new Registro().setVisible(true);
      //  new NewJFrame().setVisible(true);

    }//GEN-LAST:event_BNuevoActionPerformed

    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        this.setVisible(false);
       // new interfaz().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BCargarActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        this.setVisible(false);
        new Bienvenida().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BbackActionPerformed

    private void TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiendaActionPerformed
   
        this.setVisible(false);
        new Tienda().setVisible(true);// TODO add your handling code here:
   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCargar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton Bback;
    private javax.swing.JButton Tienda;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
