
package window;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author luedu
 */
public class Registro extends javax.swing.JFrame {

    
    // new jTable1;
    
    
    /**
     * Creates new form interfaz
     */
    
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("lueduardogr/picture/iconin.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBack = new javax.swing.JButton();
        jlNickname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        jButton3Reportes = new javax.swing.JButton();
        nickname = new javax.swing.JTextField();
        CB1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CB2 = new javax.swing.JComboBox<>();
        CB3 = new javax.swing.JComboBox<>();
        Jugar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack.setBackground(new java.awt.Color(51, 255, 51));
        jBack.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jBack.setForeground(new java.awt.Color(255, 51, 51));
        jBack.setText("Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 100, 40));

        jlNickname.setBackground(new java.awt.Color(102, 255, 102));
        jlNickname.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jlNickname.setForeground(new java.awt.Color(51, 255, 51));
        jlNickname.setText("NickName:");
        jlNickname.setAutoscrolls(true);
        getContentPane().add(jlNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Tercer Vehiculo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, -1));

        Jugar.setBackground(new java.awt.Color(102, 255, 102));
        Jugar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Jugar.setForeground(new java.awt.Color(255, 0, 51));
        Jugar.setText("Jugar");
        Jugar.setActionCommand("Ver Reportes");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, -1, -1));

        jButton3Reportes.setBackground(new java.awt.Color(102, 255, 102));
        jButton3Reportes.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton3Reportes.setForeground(new java.awt.Color(255, 0, 0));
        jButton3Reportes.setText("Ver Reportes");
        jButton3Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        nickname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        nickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 340, 30));

        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avión", "Tanque" }));
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 120, 30));

        jLabel7.setBackground(new java.awt.Color(102, 255, 102));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Primer Vehiculo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, -1));

        jLabel8.setBackground(new java.awt.Color(102, 255, 102));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("Segundo Vehiculo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, -1));

        CB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avión", "Tanque" }));
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, 30));

        CB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avión", "Tanque" }));
        CB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB3ActionPerformed(evt);
            }
        });
        getContentPane().add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 120, 30));

        Jugar1.setBackground(new java.awt.Color(102, 255, 102));
        Jugar1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Jugar1.setForeground(new java.awt.Color(255, 0, 51));
        Jugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save.png"))); // NOI18N
        Jugar1.setActionCommand("Ver Reportes");
        Jugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jugar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/WallpaperIz.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        this.setVisible(false);
        new Option().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jBackActionPerformed

    private void jButton3ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ReportesActionPerformed
        this.setVisible(false); 
       // new Reportes().setVisible(true);
    }//GEN-LAST:event_jButton3ReportesActionPerformed

    
    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
    this.setVisible(false); 
    //new Reportes().setVisible(true);
        
    System.out.println(nickname.getText());
    System.out.println(CB1.getSelectedItem()+"/");
    System.out.println(CB2.getSelectedItem()+"/");
    System.out.println(CB3.getSelectedItem()+"/");
    
    
    jTable1.agregar(nickname.getText(),CB1.getSelectedItem()+"/",CB2.getSelectedItem()+"/",CB3.getSelectedItem()+"/");
    
    
    nickname.setText("");
    
    //punteo.setText("");
    //L1.setVisible(true);
    //setVisible(false);
    //L2.setVisible(true);
    
   

        
// TODO add your handling code here:
    }//GEN-LAST:event_JugarActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB2ActionPerformed

    private void CB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB3ActionPerformed

    private void Jugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jugar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jugar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JComboBox<String> CB2;
    private javax.swing.JComboBox<String> CB3;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Jugar1;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton3Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlNickname;
    private javax.swing.JTextField nickname;
    // End of variables declaration//GEN-END:variables

}
